S01/discussion/discussion/urls.py
from django.contrib import admin
from django.urls import include, path

# Every django project always starts with the package that has the same name. In order for us to access the routes of a different package (todolist), then we have to import/include it within the 'urls.py' file within the package that has the same name as the project.
urlpatterns = [
    # By doing this, we are going to be able to access the routes from the urls.py of the todolist package.
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

S01/discussion/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'
urlpatterns = [
    path('', views.index, name='index'),

    # TodoItem URLs
    path('todoitem/<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
    path('todoitem/<int:todoitem_id>/edit/', views.update_task, name='update_task'),
    path('todoitem/<int:todoitem_id>/delete/', views.delete_task, name='delete_task'),

    # EventItem URLs
    path('eventitem/<int:eventitem_id>/', views.eventitem, name='vieweventitem'),
    path('eventitem/<int:eventitem_id>/edit/', views.update_event, name='update_event'),
    path('eventitem/<int:eventitem_id>/delete/', views.delete_event, name='delete_event'),

    # Other URLs
    path('register/', views.register, name="register"),
    # path('change_password/', views.change_password, name="change_password"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('add_task/', views.add_task, name="add_task"),
    path('add_event/', views.add_event, name="add_event"),
    path('update_profile/<int:user_id>/', views.update_profile, name="update_profile")
]

S01/discussion/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} To Do App {% endblock %}</title>
	<!-- Bootstrap -->
	 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
	{% include 'navbar.html' %}
	{% block content %}
	{% endblock %}

	<!-- Bootstrap Script -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

S01/discussion/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid ">
    <a class="navbar-brand  " href="#">To Do App</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse  " id="navbarNav">
      <ul class="navbar-nav ms-auto ">
        {% if user.is_authenticated%}
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'todolist:index' %}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:add_event' %}">Add Event</a>
        </li>
        {% endif %}
        <li class="nav-item">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'todolist:update_profile' user_id=request.user.id %}">Update Profile</a>
          {% endif %}

        </li>
        {% if not user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:login' %}">Login</a>
        </li>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
        </li>
        {% endif %}
        {% if user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>