S01/discussion/discussion/urls.py
from django.contrib import admin
from django.urls import include, path

# Every django project always starts with the package that has the same name. In order for us to access the routes of a different package (todolist), then we have to import/include it within the 'urls.py' file within the package that has the same name as the project.
urlpatterns = [
    # By doing this, we are going to be able to access the routes from the urls.py of the todolist package.
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

S01/discussion/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'
urlpatterns = [
    path('', views.index, name='index'),

    # TodoItem URLs
    path('todoitem/<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
    path('todoitem/<int:todoitem_id>/edit/', views.update_task, name='update_task'),
    path('todoitem/<int:todoitem_id>/delete/', views.delete_task, name='delete_task'),

    # EventItem URLs
    path('eventitem/<int:eventitem_id>/', views.eventitem, name='vieweventitem'),
    path('eventitem/<int:eventitem_id>/edit/', views.update_event, name='update_event'),
    path('eventitem/<int:eventitem_id>/delete/', views.delete_event, name='delete_event'),

    # Other URLs
    path('register/', views.register, name="register"),
    # path('change_password/', views.change_password, name="change_password"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('add_task/', views.add_task, name="add_task"),
    path('add_event/', views.add_event, name="add_event"),
    path('update_profile/<int:user_id>/', views.update_profile, name="update_profile")
]

S01/discussion/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField("date created")
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class EventList(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	event_date = models.DateTimeField("date created")
	user_is = models.ForeignKey(User, on_delete=models.CASCADE, default="")

S01/discussion/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label="Username", max_length=200)
	password = forms.CharField(label="Password", max_length=200)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label="Task Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	status = forms.CharField(label="Status", max_length=50)

class UpdateEventForm(forms.Form):
	event_name = forms.CharField(label="Event Name", max_length=50)
	description = forms.CharField(label="Description", max_length=200)
	status = forms.CharField(label="Status", max_length=50)

class UpdateProfileForm(forms.Form):
	first_name = forms.CharField(label="First Name", max_length=100)
	last_name = forms.CharField(label="Last Name", max_length=100)
	password = forms.CharField(label="Password", required=False)
class RegisterForm(forms.Form):
	user_name = forms.CharField(label="Username", max_length=50)
	user_fname = forms.CharField(label="First Name", max_length=50)
	user_lname = forms.CharField(label="Last Name", max_length=100)
	email = forms.EmailField(label="Email", max_length=100)
	password = forms.CharField(label="Password", max_length=50)
	con_password = forms.CharField(label="Confirm Password", max_length=50)

S01/discussion/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.forms.models import model_to_dict
from django.utils import timezone
from django.contrib.auth.hashers import make_password

# from django.template import loader

# Local import
from .models import ToDoItem, EventList
from .forms import LoginForm, AddTaskForm, AddEventForm, UpdateTaskForm, UpdateEventForm, RegisterForm, UpdateProfileForm

# Create your views here.
def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	eventitem_list = EventList.objects.filter(user_is_id=request.user.id)
	# output = ', '.join([todoitem.task_name for todoitem in todoitem_list])
	# template = loader.get_template("todolist/index.html")
	# context = {'todoitem_list' : todoitem_list}
	# return HttpResponse(template.render(context, request))

	# simplier way
	context = { 
	'eventitem_list' : eventitem_list,
	'todoitem_list' : todoitem_list,
	'user' : request.user
	}
	return render(request, "todolist/index.html", context)
# for todoitem
def todoitem(request, todoitem_id):
	# response = "You are viewing the details of %s"
	# return HttpResponse(response % todoitem_id)
	# The model_to_dict() allows to convert models into dictionaries
	# get() allows to retrive a record using it primary key(pk)
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

# this is for eventlist
def eventitem(request, eventitem_id):
	eventitem = get_object_or_404(EventList, pk=eventitem_id)
	return render(request, "todolist/eventitem.html", model_to_dict(eventitem))

def register(request):
	context = {}

	if request.method == 'POST':
		form = RegisterForm(request.POST)

		if form.is_valid():
			user_name = form.cleaned_data['user_name']
			user_fname = form.cleaned_data['user_fname']
			user_lname = form.cleaned_data['user_lname']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']


			con_password = form.cleaned_data['con_password']

			if password == con_password:
				
				# con_password = form.cleaned_data['con_password']
				duplicates = User.objects.filter(email=email)

				if not duplicates:
					# print(hashed_password)
					
					hashed_password = make_password(password)
					new_user = User(
						username = user_name,
						first_name = user_fname,
						last_name = user_lname,
						email = email,
						password = hashed_password
					)
					new_user.save()
					return redirect("todolist:login")
				else:
					context = {
						"error": True
					}
			else:
				context = {
					"password_mismatched": True
				}
		else:
			context = {
					"is_form_invalid": True
				}
				
	return render(request, "todolist/register.html", context)


def update_profile(request, user_id):
		
	user = User.objects.filter(pk=user_id)

	if not user:

		context = {
			"error" : True
		}
	else:
		if request.method == 'POST':
			form = UpdateProfileForm(request.POST)

			if form.is_valid() == False:
				form = UpdateProfileForm()

			else:
				first_name = form.cleaned_data['first_name']
				last_name = form.cleaned_data['last_name']
				password = form.cleaned_data['password']

				user[0].first_name = first_name
				user[0].last_name = last_name

				if password:
					user[0].set_password(password)
					user[0].save()
					update_session_auth_hash(request, user[0])
					return redirect("todolist:login")

				else:
					user[0].save()
					
				return redirect("todolist:index")
				
			
		context = {
			"user" : request.user,
			"user_id" : user_id,
			"first_name" : user[0].first_name,
			"last_name" : user[0].last_name
		}
		
	return render(request, "todolist/update_profile.html", context)

def login_view(request):
	context = {}

	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()

		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user = authenticate(request, username=username, password=password)

			print(user)

			if user is not None: 
			# Save creates a record in the django_session table in the database
				print(user.password)
				login(request, user)
				# redirect the user to the index.html page
				return redirect("todolist:index")
			else:
				print("user is correct password is mismatched")
				context = {
					"error" : True
					}
	
	return render(request, "todolist/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("todolist:login")

def add_task(request):

	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)

		if form.is_valid() == False:
			form = AddTaskForm()
		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			# Checks if a task already exists in the database
			user = request.user
			duplicates = ToDoItem.objects.filter(user=user, task_name=task_name)

			if not duplicates:

				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")
			
			else:

				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def add_event(request):

	context = {}

	if request.method == 'POST':
		form = AddEventForm(request.POST)

		if form.is_valid() == False:
			form = AddEventForm()
		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']

			user = request.user
			duplicates = EventList.objects.filter(user_is=user, event_name=event_name)

			if not duplicates:
				EventList.objects.create(event_name=event_name, description=description, event_date=timezone.now(), user_is_id=request.user.id)
				return redirect("todolist:index")
			else:
				context = {
					"error" : True
				}

	return render(request, "todolist/add_event.html", context)

def update_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user" : request.user,
		"todoitem_id" : todoitem_id,
		"task_name" : todoitem[0].task_name,
		"description" : todoitem[0].task_name,
		"status" : todoitem[0].status
	}

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:
			form = UpdateTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

		if todoitem:
			todoitem[0].task_name = task_name
			todoitem[0].description = description
			todoitem[0].status = status
			todoitem[0].save()
			return redirect("todolist:index")

		else:

			context = {
				"error" : True
			}

	return render(request, 'todolist/update_task.html', context)

def update_event(request, eventitem_id):

	eventitem = EventList.objects.filter(pk=eventitem_id)

	context = {
		"user" : request.user,
		"eventitem_id" : eventitem_id,
		"event_name" : eventitem[0].event_name,
		"description" : eventitem[0].description,
		"status" : eventitem[0].status
	}

	if request.method == 'POST':
		form = UpdateEventForm(request.POST)

		if form.is_valid() == False:
			form = UpdateEventForm()
		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']
		
		if eventitem:
			eventitem[0].event_name = event_name
			eventitem[0].description = description
			eventitem[0].status = status
			eventitem[0].save()
			return redirect("todolist:index")
		else:
			context = {
				"error" : True
			}

	return render(request, 'todolist/update_event.html', context)

def delete_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()

	return redirect("todolist:index")

def delete_event(request, eventitem_id):

	eventitem = EventList.objects.filter(pk=eventitem_id).delete()

	return redirect("todolist:index")

S01/discussion/todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
{% if user.is_anonymous == False %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Add an Event</h1>
			{% if error == True %}
				<p class="text-danger">Duplicate event found!</p>
			{% endif %}

			<form action="{% url 'todolist:add_event' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					  <label for="event_name" class="form-label">Task Name:</label>
					  <input type="text" class="form-control" id="event_name" value="{{event_name}}" name="event_name" maxlength="50" required>
				</div>

				<div class="mb-3">
					  <label for="description" class="form-label">Description:</label>
					  <textarea class="form-control" id="description" value="{{description}}" name="description" required></textarea>
				</div>

				<div class="mb-3">
					  <input class="btn btn-success" type="submit" value="Add Task">
				</div>
		</div>
	</div>
</div>

		{% else %}
			<h1 class="tex-center my-3">You are not authorized to access this page.</h1>
			<p class="">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>

		{% endif %}

{% endblock %}

S01/discussion/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
{% if user.is_anonymous == False %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Add a Task</h1>
			{% if error == True %}
				<p class="text-danger">Duplicate task found!</p>
			{% endif %}

			<form action="{% url 'todolist:add_task' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					  <label for="task_name" class="form-label">Task Name:</label>
					  <input type="text" class="form-control" id="task_name" value="{{task_name}}" name="task_name" maxlength="50" required>
				</div>

				<div class="mb-3">
					  <label for="description" class="form-label">Description:</label>
					  <textarea class="form-control" id="description" value="{{description}}" name="description" required></textarea>
				</div>

				<div class="mb-3">
					  <input class="btn btn-success" type="submit" value="Add Task">
				</div>
		</div>
	</div>
</div>

		{% else %}
			<h1 class="tex-center my-3">You are not authorized to access this page.</h1>
			<p class="">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>

		{% endif %}

{% endblock %}

S01/discussion/todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password are correct</p>

{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated</p>
{% endif %}

S01/discussion/todolist/templates/todolist/eventitem.html
{% extends 'base.html' %}

{% block title %}Event{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ event_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>
	<button class="btn btn-primary mx-1 text-decoration-none"><a href="{% url 'todolist:update_event' id %}" class="text-light">Edit Task</a></button>

	<button class="btn btn-danger mx-1 text-decoration-none"><a href="{% url 'todolist:delete_event' id %}" class="text-light">Delete Task</a></button>

	<button class="btn btn-warning mx-1 text-decoration-none"><a href="{% url 'todolist:index' %}" class="text-light">Back to Tasks</a></button>
</div>

{% endblock %}

S01/discussion/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
	{% if user.is_anonymous == False%}
		<h1 class="text-center">Welcome {{user.first_name}} {{user.last_name}}!</h1>

		<h3 class="text-center">My Task</h3>
		{% if not todoitem_list %}
       		 <p class="text-center">No tasks have been created.</p>
   		{% else %}
		<ul class="text-center list-unstyled ">
			{% for todoitem in todoitem_list %}
				<li class="border p-2 col-2 mx-auto">
					<a class="text-decoration-none text-dark" href="{% url 'todolist:viewtodoitem' todoitem.id %}">{{todoitem.task_name}}</a>
				</li>
			{% endfor %}
		</ul>
		{% endif %}
		<h3 class="text-center">My Event</h3>
		{% if not eventitem_list %}
			<p class="text-center">No task have been created</p>
		{% else %}
		<ul class="text-center list-unstyled">
			{% for eventitem in eventitem_list %}
				<li class="border p-2 col-2 mx-auto">
					<a class="text-decoration-none text-dark" href="{% url 'todolist:vieweventitem' eventitem.id %}">{{eventitem.event_name}}</a>
				</li>
			{% endfor %}
		</ul>
		{% endif %}
	{% elif user.is_anonymous == True %}
		<h1>You are not authorized to access this page.</h1>
		<p>Kindly login <a href="login">here</a></p>
		
	{% else %}
		<h1 class="text-center">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<h3 class="text-center">My Task</h3>
		<p class="text-center">No Events have been created</p>
		<h3 class="text-center">My Event</h3>
		<p class="text-center">No Events have been created</p>

	{% endif %}

{% endblock %}

S01/discussion/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% if user.is_anonymous == True %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials. Please check your username and password</p>
			{% endif %}

			<form action="{% url 'todolist:login' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					  <label for="username" class="form-label">Username:</label>
					  <input type="text" class="form-control" id="username"  name="username" maxlength="20" required>
				</div>

				<div class="mb-3">
					  <label for="password" class="form-label">Password:</label>
					  <input type="password" class="form-control" id="password"  name="password" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Login">
				</div>

			</form>
		</div>
	</div>
</div>

		{% else %}
			<h1 class="tex-center my-3">You are not authorized to access this page.</h1>
			<p class="">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>

		{% endif %}

{% endblock %}

S01/discussion/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}register{% endblock %}

{% block content %}
{% if user.is_anonymous == True %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Register</h1>
			{% if error == True %}
			    <p class="text-danger">Duplicate user found!</p>
			{% elif password_mismatched == True %}
			    <p class="text-danger">Password mismatched! Please register again.</p>
			{% elif is_form_invalid == True %}
			    <p class="text-danger">Invalid Email! Please register again.</p>
			{% endif %}

			<form action="{% url 'todolist:register' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					   <label for="user_name" class="form-label">User Name:</label>
					   <input type="text" class="form-control" id="user_name" name="user_name"  value="{{ user_name }}" maxlength="50" required>
						</div>		

				<div class="mb-3">
					  <label for="user_fname" class="form-label">First Name:</label>
					  <input class="form-control" id="user_fname"  name="user_fname" value="{{ user_fname }}" required></input>
				</div>

				<div class="mb-3">
					  <label for="user_lname" class="form-label">Last Name:</label>
					  <input type="text" class="form-control" id="user_lname"  name="user_lname"  value="{{ user_lname }}" maxlength="50" required>
				</div>

				<div class="mb-3">
					  <label for="email" class="form-label">Email:</label>
					  <input class="form-control" id="email" name="email"  value="{{ email }}" required></input>
				</div>

				<div class="mb-3">
					  <label for="password" class="form-label">Password:</label>
					  <input type="password" class="form-control" id="password"  name="password"  maxlength="50" required>
				</div>

	 			<div class="mb-3">
					  <label for="con_password" class="form-label">Confirm Password:</label>
					  <input type="password" class="form-control" id="con_password" name="con_password" maxlength="50" required>
				</div> 

				<div class="mb-3">
					  <input class="btn btn-success" type="submit" value="Register">
				</div>
		</div>
	</div>
</div>

		{% else %}
			<h1 class="tex-center my-3">You are not authorized to access this page.</h1>
			<p class="">Go back to home <a href="{% url 'todolist:index' %}">here</a></p>

		{% endif %}

{% endblock %}

S01/discussion/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}Task{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ task_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>
	<button class="btn btn-primary mx-1 text-decoration-none"><a href="{% url 'todolist:update_task' id %}" class="text-light">Edit Task</a></button>

	<button class="btn btn-danger mx-1 text-decoration-none"><a href="{% url 'todolist:delete_task' id %}" class="text-light">Delete Task</a></button>

	<button class="btn btn-warning mx-1 text-decoration-none"><a href="{% url 'todolist:index' %}" class="text-light">Back to Tasks</a></button>
</div>

{% endblock %}

S01/discussion/todolist/templates/todolist/update_event.html
{% extends 'base.html' %}

{% block title %}Update Event{% endblock %}

{% block content %}

	{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center">Update Event</h1>
					{% if error == True %}
						<p class="text-danger">Event not found</p>
					{% endif %}

					<form action="{% url 'todolist:update_event' eventitem_id %}" method="post">
						<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
						<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
						{% csrf_token %}

						<div class="mb-3">
							<label for="event_name" class="form-label">Event Name:</label>
							<input type="text" class="form-control" id="event_name" name="event_name" value="{{event_name}}" maxlength="50" required>
						</div>

						<div class="mb-3">
							<label for="description" class="form-label">Description:</label>
							<textarea class="form-control" id="description" name="description" value="{{description}}" required>{{ description }}</textarea>
						</div>

						<div class="mb-3">
							<label for="status" class="form-label">Status:</label>
							<input class="form-control" id="status" name="status" value="{{status}}" required></input>
						</div>

						<div class="mb-3">					
							<input class="btn btn-success" type="submit" value="Update Event">
						</div>

					</form>
				</div>
			</div>
		</div>

		{% else %}
			<h1 class="tex-center my-3">You are not authorized to access this page.</h1>
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>

		{% endif %}
{% endblock %}

S01/discussion/todolist/templates/todolist/update_profile.html
{% extends 'base.html' %}

{% block title %}Update Profile{% endblock %}

{% block content %}

{% if user.is_anonymous == False %}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center">Update Profile</h1>
            <form action="{% url 'todolist:update_profile' user_id=user_id %}" method="post">
                <!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
                <!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
                {% csrf_token %}

                <div class="mb-3">
                    <label for="first_name" class="form-label">First Name:</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" value="{{first_name}}" maxlength="100" required>
                </div>

                <div class="mb-3">
                    <label for="last_name" class="form-label">Last Name:</label>
                    <input class="form-control" id="last_name" name="last_name" value="{{last_name}}" required></input>
                </div>

                <div class="mb-3">
                    <label for="password" class="form-label">Password:</label>
                    <input type="password" class="form-control" id="password" name="password" value="{{password}}" ></input>
                </div>

                <div class="mb-3">					
                    <input class="btn btn-success" type="submit" value="Update Profile">
                </div>

            </form>
        </div>
    </div>
</div>


{% else %}

<h1 class="tex-center my-3">You are not authorized to access this page.</h1>
<p class="">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>

{% endif %}


{% endblock %}

S01/discussion/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}

	{% if user.is_anonymous == False %}
		<div class="container">
			<div class="row">
				<div class="col-6 offset-3">
					<h1 class="text-center">Update Task</h1>
					{% if error == True %}
						<p class="text-danger">Task not found</p>
					{% endif %}

					<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
						<!-- This template tag provides protection against Cross Site Request Forgeries (CSRF) -->
						<!-- CSRF occurs when a malicious website contains a link, a form button or some JavaScript that is intended to perform some action our website, using the credentials of a logged-in user -->
						{% csrf_token %}

						<div class="mb-3">
							<label for="task_name" class="form-label">Task Name:</label>
							<input type="text" class="form-control" id="task_name" name="task_name" value="{{task_name}}" maxlength="50" required>
						</div>

						<div class="mb-3">
							<label for="description" class="form-label">Description:</label>
							<textarea class="form-control" id="description" name="description" value="{{description}}" required>{{ description }}</textarea>
						</div>

						<div class="mb-3">
							<label for="status" class="form-label">Status:</label>
							<input class="form-control" id="status" name="status" value="{{status}}" required></input>
						</div>

						<div class="mb-3">					
							<input class="btn btn-success" type="submit" value="Update Task">
						</div>

					</form>
				</div>
			</div>
		</div>

		{% else %}
			<h1 class="tex-center my-3">You are not authorized to access this page.</h1>
			<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>

		{% endif %}
{% endblock %}